sudo: required
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
script:
- bolt execute-unit-tests
- bolt execute-feature-tests
- if [[ $TRAVIS_PYTHON_VERSION != '3.3' ]]; then make -C docs html; fi
notifications:
  slack:
    secure: um1fqygbv7EDw8BjN5yk8Al5XdTXFY971dSTO6w3LMGVYWFDna/4fH7UUU/SZZQ/tQyfQ1xy+xIhFBoqIpcNV2FNpF4J6hNOULwBHMesEWUNaoaSWx2dRxrsEdKmLQ7iO4PnpAs6QcXOpYuXUqJSPB6Lg0G85KFRk79fROtrD5IrhmduLtyDEp2WOSKqL8DuFqEa+cg+IIEUGRAWjP6Aqhcb/RuEstmaIeI9eBtGK0gcxagcFGZuDfE9HVAANpQKGINpTxlM46rGb0pFs3UpbtxoyElqH8jRZGxw++PRbbkyI37on25nlJvdYujza6gnYWs9XiaMTeV/6Rq7RQgXPbO9ykmNG4naracG+oHRtbS7q3Crlc2u1KsUAiSUouh+Rh0KPmT58S7O4V7f7ZmIi9R+4kzAHURtvtTpO4fXwCLZ4ww5CDUKW9JiK0O9TPjT0ep3Ssrnp0jwx3s9R0wtzbE6CoyB3Tl/OrkI91L3o4qgjXRWBYNnFhlSlesDonEpX2/EIOEG0TVDRWWC+hePOxT8mGwFb/mYjvOy14JmcrDnFCoUo2Acp6g+DUEwf8WKpiq80i4Om5EjeoqQIBizcvmaGv0HqlhffE8A3gmTQv1rk3/CutIHE7qK/CJrbUYeqEMjdSsa7cr51zA8pSDXEYKFFI8eK8Fc7bwQQozv9YE=
